#!/bin/bash

if [[ -d /tmp/daws ]]
then
  DOCKER_HOST= docker run -v $HOME/.aws:/root/.aws -v /tmp/daws:/tmp/daws safelayer/awscli $@
else
  DOCKER_HOST= docker run -v $HOME/.aws:/root/.aws safelayer/awscli $@
fi
